ALTER TABLE ORDERDISHES ADD COLUMN dishType VARCHAR(100) DEFAULT 'OTHERS';
ALTER TABLE CHECKS ADD COLUMN deliveryTime TIMESTAMP;

CREATE TABLE DELIVERYAREAS
(
    id INT PRIMARY KEY AUTO_INCREMENT,
    userId INT,
    name VARCHAR(200)
);

ALTER TABLE CHECKS ADD COLUMN deliveryArea VARCHAR(300) DEFAULT 'Others';
ALTER TABLE CHECKS ADD COLUMN deliveryAddress VARCHAR(300) DEFAULT '';